### ISSUE TITLE
Investigate slowness of edu.ucdavis.dss.ipa.api.components.course.CourseViewController.createMultipleCoursesFromDW()

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1115]
Branch 'dw-course-import'
-------------------

According to New Relic, this call can take up to 50s to return, which is way, way too long.

In particular, there is a MySQL 'terms' select that is called over 159,000 times responsible for about 27s of that transaction.

The course mass import also doesn't play nicely with our server warnings: I received a "server failed" message after the request took too long even though the request succeeded. We need to address that user experience.

**Comment by cthielen** [comment]
I tried importing all of 'MAT' subject code into an empty schedule today and IPA client reported an error after waiting a while saying "Request appears to have failed." I did not receive an exception e-mail and could not find anything in the logs. I think the request simply "timed out" from IPA's perspective.

We probably want to not only fix this function but up the amount of time the IPA client waits. Technically, sockets have their own time outs and don't need us to mangle our on top of that.

**Comment by ltwheeler** [comment]
After some tweaks I dropped course import time from 83 seconds to 7 seconds. It will still occasionally hit the 'server is taking longer than usual' yellow warning, but shouldn't hit an error again.

banner - PSC - 2017-18 (124 courses)
previously:
standard: (83 seconds)
with day/time: (152 seconds)

after changes:
standard: (7 seconds)
with day/time: (12 seconds)
