### ISSUE TITLE
Assignments View: Excel download should match the by instructor/course pivot selection

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1168]
Fixed on 'excel-add-units'
----

PR:
https://github.com/ucdavis/ipa-web/pull/203

From user:
When you export this page to excel, it is sorted by class – NEEDS to be sorted by instructor: https://ipa.ucdavis.edu/assignments/12/2017?tab=instructors

**Comment by cthielen** [comment]
Requested by Caitlyn

**Comment by cthielen** [comment]
Also requested by Meshell L of Computer Science
