### ISSUE TITLE
Instructor View: Ability to explicitly assign 'AI Placeholder' as the instructor of a course

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1214]
Customer(s): Mandy H

This would be similar to the ability to assign 'The Staff' (i.e. a virtual person) but would instead read 'AI Placeholder'.

This could tie into the instructional support page.

**Comment by ltwheeler** [comment]
1) Always display an option on sectionGroup to assign AI placeholder, will create a 50% appointment AI by default
2) For each AI slot assigned to the sectiongroup (and unfilled),
display an assigned 'AI placeholder' (ignore filled ai slots, they are covered by a proper teachingAssignment)
3) The 'assigned AI placeholder' will have a delete button like normal, that will delete that placeholder
