### ISSUE TITLE
SupportCall: Make comments by course preference (optionally) required

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1220]
From User:
I would still like to make comments by course preference a required field in the support call, if possible.

**Comment by ltwheeler** [comment]
From Christal

**Comment by cthielen** [comment]
Flag defaulting to false to require course comments on a Support Call. This would make the comments link on the Support Staff-facing form red until a comment existed. This would validate the form and not allow submission unless a comment was left. It is important to have text indicating that "Your department is requiring a comment on all course preferences" or something to that effect.

**Comment by ltwheeler** [comment]
Remove red coloring from comment modal button
