### ISSUE TITLE
Scheduling View: Should not allow activities with zero duration

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1332]
Fixed on branch 'zero-duration-activity'
------------
Additional features:
1) gray out arrows when disabled
2) Investigate bug in demo where I was able to push the start time ahead of end time when clicking on minute selector (8:00am - 8:05am)
----
Original issue title: Scheduling View: Selecting an activity via the calendar results in unset time selectors

Expected result: If I select an activity via the calendar, the information on the left, including the time selectors (50 min, 80 min, etc.) should be filled in correctly.

**Comment by ltwheeler** [comment]
On closer inspection,
What happens is when an activity has start 9am, end 9am, it has a duration of 0 minutes, which makes the standard time selector reject it as valid. The freeform selector has no issue with this, even though the data doesn't make sense.

We need to:
1) write a migration to nullify start/end times on activities where the start and end match
2) Change backend logic to not allow identical start/end times
3) Change frontend UI to not allow identical start/end times

**Comment by cthielen** [comment]
The migration needs to mimic the existing data, e.g. if a 9 AM to 9 AM course appeared to start at 9 AM but rendered as say, 50 minutes, the migration shouldn't remove the activity but should simply set the end time to a proper 9:50.

50 minutes is a guess. We need to investigate the previous behavior.
