### ISSUE TITLE
2 | Scheduling View: Color activities on the calendar using the color of associated tags

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1338]
Fixed on 'calendar-tag-color'
-------------
A number of schedulers use many colors on their calendars to better understand the information. These colors are typically what we call tag colors. Let's color the activity blocks on the calendar with their associated tag color.

We'll have to make a decision for what to do with multiple tags but I think if we just use the first tag, that's good enough for 95% of cases (I don't think multi-tags are that common).

**Comment by cthielen** [comment]
SOE is one such scheduler that would appreciate this.

**Comment by ltwheeler** [comment]
Currently IPA does the following for the 3 kinds of visibility/course selection
<img width="774" alt="screen shot 2017-11-08 at 3 04 25 pm" src="https://user-images.githubusercontent.com/1776859/32579698-f5048276-c496-11e7-8a05-d04ea7708291.png">
<img width="762" alt="screen shot 2017-11-08 at 3 04 31 pm" src="https://user-images.githubusercontent.com/1776859/32579701-f6a908ae-c496-11e7-8238-6bd83405f6b5.png">
<img width="746" alt="screen shot 2017-11-08 at 3 04 35 pm" src="https://user-images.githubusercontent.com/1776859/32579704-f9017794-c496-11e7-83d8-97f06e8498cc.png">


The current change looks like this:
<img width="1149" alt="screen shot 2017-11-08 at 3 10 03 pm" src="https://user-images.githubusercontent.com/1776859/32579733-150438c8-c497-11e7-8724-acb9b3ee50fb.png">
<img width="1191" alt="screen shot 2017-11-08 at 3 10 08 pm" src="https://user-images.githubusercontent.com/1776859/32579737-17c1b856-c497-11e7-8658-fd872b4781de.png">
<img width="1166" alt="screen shot 2017-11-08 at 3 10 13 pm" src="https://user-images.githubusercontent.com/1776859/32579741-1a212b7c-c497-11e7-8523-e2fa63210631.png">

**Comment by ltwheeler** [comment]
IPA's current behavior is a little strange, with no visual change after selecting a sectionGroup (picture 2).

I think selecting a sectionGroup should do something, but unclear what. going from red -> gray -> teal may not be best.

**Comment by cthielen** [comment]
It might be best to change the 'selected' activity indicator to be border-based instead.

**Comment by cthielen** [comment]
Perhaps a 2 or 3px blue border for everything in the SG and a 4 or 5 px blue border (the grey blue IPA uses) for the highlighted activity specifically? This will need to be messed around with.

**Comment by cthielen** [comment]
Let's leave this issue open until the 'Filter' tags are in the proper colors too.
