### ISSUE TITLE
Various 'Summary' pages do not appear/disappear correctly when adding/removing a role

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1354]
For example, Kerry added herself as an instructor but even after log out / log in, the instructor summary screen didn't appear.

Likewise, I took everything away from myself except AC and could still see other summary screens.

**Comment by ltwheeler** [comment]
I can't see to replicate this bug.

1) I went to production, removed all roles from myself except academic coordinator in dss it.
2) Logged in, I saw only academic coordinator summary.
3) Went to dss it workgroup page, added senate instructor role to myself.
4) Hit the home button, the summary page showed both instructor and academic coordinator versions.
5) Went back to workgroup page, removed instructor role.
6) Hit the home button, the summary page showed just academic coordinator version again.

**Comment by ltwheeler** [comment]
In further testing, we cannot reproduce. Will close for now, and watch for future occurrences.
