### ISSUE TITLE
submitMassAssignTags: cannot read property tagIds of undefined

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1430]
URL: https://ipa.ucdavis.edu/courses/18/2018 User: Friedrich, Leanna Kerberos: lfriedri Full Error: Cannot read property 'tagIds' of undefined Stack: TypeError: Cannot read property 'tagIds' of undefined at https://ipa.ucdavis.edu/js/courseApp.js?rel=1510259909729:8:3424 at Array.forEach () at https://ipa.ucdavis.edu/js/courseApp.js?rel=1510259909729:8:3393 at Array.forEach () at Object._courseReducers (https://ipa.ucdavis.edu/js/courseApp.js?rel=1510259909729:8:3320) at Object.reduce (https://ipa.ucdavis.edu/js/courseApp.js?rel=1510259909729:8:13240) at courseService.submitMassAssignTags.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/courseApp.js?rel=1510259909729:7:14082) at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272) at https://ipa.ucdavis.edu/js/lib.js:14:6539 at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)

**Comment by ltwheeler** [comment]
Cannot replicate:
The line in question triggering the error is 146 in courseStateService.js,
Course is retrieved by id, and is not found for some reason, resulting in a null object.

**Comment by cthielen** [comment]
That was the scenario I was going to suggest. The other thing to look into is whether action.massAssignTags.courseIds is validating courseIds as they're added, or if it's possible a null value is being added to the list and we don't realize it.
