### ISSUE TITLE
Backend logic error while importing activities from Banner

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1443]
Fixed on 'import-from-banner'
----
Error while importing PHI courses _with_activities_ from Banner for 2018-19 into an empty IPA schedule for 2018-19. Server returns 400, no exception message on backend.

Frontend receives response:

{"errors":[{"code":"Invalid Activity","message":"Invalid Activity"}]}

This does not occur when you do not import activities.

**Comment by ltwheeler** [comment]
When importing banner activity times, the backend was erroneously setting start and end time based on the start time of the banner activity.
