### ISSUE TITLE
SupportAssignments: comments display bug during review

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1474]
Fixed on 'fix-preference-comment'
----
related PR:
https://github.com/ucdavis/ipa-client-angular/pull/1475

During a supportAssignment review if an instructor looks at the by support staff pivot, preferences that have lengthy comments will be displayed incorrectly and bleed outside the box.

**Comment by cthielen** [comment]
Please add more detail so one can re-discover the issue.

**Comment by ltwheeler** [comment]
![error](https://user-images.githubusercontent.com/1776859/33498120-1b70b934-d685-11e7-9413-212d4ae3b8d5.jpg)
