### ISSUE TITLE
Ability to send a test Teaching Call

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#430]
One academic planner mentioned it would be nice to send a test e-mail showing what the Teaching Call would look like. Presumably this would send a single e-mail to the individual who is logged in and creating the Teaching Call.

A basic version of this would make an AJAX call to send the e-mail and the user would have to wait with their browser and modal open to see the e-mail. A more sophisticated implementation would allow Teaching Calls to be created but not sent until the user re-visits the page and decides to start it. The latter is interesting but we should discuss its usefulness.

**Comment by ltwheeler** [comment]
This use case is now handled by the teaching call redesign for granular communication
