### ISSUE TITLE
Teaching Call Form: Add AJAX spinner after preference is selected to indicate the 1-2s wait is normal

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#528]
When an instructor selects a teaching preference there is a 1-2 second delay. The dropdown collapses, and then the wait begins.

Let's add an AJAX spinner to the "Add Preference" box that will go away when the server response comes back. This way it doesn't feel like the web application has failed or erred out in the background.

**Comment by ltwheeler** [comment]
Resolved in teaching call form redesign
