### ISSUE TITLE
It is not straightforward to get to the teaching call as an instructor

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#551]
An instructor was unable to find their teachingCall by going to ipa directly. This is not surprising as it defaults to putting you in the current academic year.

For Instructors (and in the future graduate students), perhaps their summary screen should list all active teachingCalls (where today falls between the start and end date), regardless of the 'year' selected?

**Comment by cthielen** [comment]
Hopefully fixed by new design #1307
