### ISSUE TITLE
Ability to add/remove specific individuals in a Teaching Call

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#579]
The "Federation" and "Senate" buttons could be changed to simply "Add All Federation" and "Add All Senate" to the list. The list itself would have a typeahead to search for new individuals from their workgroup, as well as the ability to remove specific individuals.

We would still need to ensure an individual is not in a TC twice. If a new TC is being created with Professor X but Professor X already has a TC out, his or her name should appear but perhaps be grey or struck out with an explanation in a tooltip-based info box off to the side ("?").

**Comment by cthielen** [comment]
This has come up with at least two customers, possibly more. We should implement it so the functionality is in line with what is found in the ISS modal.

**Comment by ltwheeler** [comment]
Addressed in #790
