### ISSUE TITLE
Ability to add/remove specific individuals from an Instructional Support Call

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#580]
The grad buttons could be changed to simply mean "Add All ____" to the list. The list itself would have a typeahead to search for new individuals from their workgroup, as well as the ability to remove specific individuals.

We would still need to ensure an individual is not in an ISSC twice. If a new ISSC is being created with Grad Student X but Grad Student X already has a ISSC out, his or her name should appear but perhaps be grey or struck out with an explanation in a tooltip-based info box off to the side ("?").

**Comment by ltwheeler** [comment]
Resolved in support call redesign
