### ISSUE TITLE
Teaching Call Undefined error

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#685]
URL: https://ipa.ucdavis.edu/assignments/18/2017?tab=courses

User: Gibson, Anya

Kerberos: abschwin

Full Error: $scope.view.state.teachingCalls is undefined

Stack: this.TeachingCallStatusCtrl/$scope.prepareTeachingCallStatusPage@https://ipa.ucdavis.edu/js/assignmentApp.js:6:30131
this.TeachingCallStatusCtrl/<@https://ipa.ucdavis.edu/js/assignmentApp.js:6:28795
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://ipa.ucdavis.edu/js/lib.js:14:21536
.reduce@https://ipa.ucdavis.edu/js/assignmentApp.js:8:26106
.showCourses@https://ipa.ucdavis.edu/js/assignmentApp.js:7:28811
this.AssignmentCtrl/$scope.showCourses@https://ipa.ucdavis.edu/js/assignmentApp.js:6:2526
this.AssignmentCtrl/$scope.setActiveTab@https://ipa.ucdavis.edu/js/assignmentApp.js:6:6944
this.AssignmentCtrl@https://ipa.ucdavis.edu/js/assignmentApp.js:6:6967
instantiate@https://ipa.ucdavis.edu/js/lib.js:11:4837
$ControllerProvider/this.$get</<@https://ipa.ucdavis.edu/js/lib.js:12:29212
ngViewFillContentFactory/<.link@https://ipa.ucdavis.edu/js/lib.js:24:24726
bind/<@https://ipa.ucdavis.edu/js/lib.js:10:9826
invokeLinkFn@https://ipa.ucdavis.edu/js/lib.js:12:19359
nodeLinkFn@https://ipa.ucdavis.edu/js/lib.js:12:1431
compositeLinkFn@https://ipa.ucdavis.edu/js/lib.js:11:23122
compile/<@https://ipa.ucdavis.edu/js/lib.js:11:21831
compilationGenerator/<@https://ipa.ucdavis.edu/js/lib.js:11:28340
boundTranscludeFn@https://ipa.ucdavis.edu/js/lib.js:11:24467
controllersBoundTransclude@https://ipa.ucdavis.edu/js/lib.js:11:29636
update@https://ipa.ucdavis.edu/js/lib.js:24:23884
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://ipa.ucdavis.edu/js/lib.js:14:22226
commitRoute/<@https://ipa.ucdavis.edu/js/lib.js:24:20735
processQueue@https://ipa.ucdavis.edu/js/lib.js:14:6272
scheduleProcessQueue/<@https://ipa.ucdavis.edu/js/lib.js:14:6539
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://ipa.ucdavis.edu/js/lib.js:14:19934
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://ipa.ucdavis.edu/js/lib.js:14:17619
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://ipa.ucdavis.edu/js/lib.js:14:20361
$LocationProvider/this.$get</<@https://ipa.ucdavis.edu/js/lib.js:13:22529
jQuery.event.dispatch@https://ipa.ucdavis.edu/js/lib.js:8:12017
jQuery.event.add/elemData.handle@https://ipa.ucdavis.edu/js/lib.js:8:8960

**Comment by cthielen** [comment]
I'm guessing this code was removed in the TC redesign and/or the issue hasn't really come up since.
