### ISSUE TITLE
Teaching Call Manual Reminder E-mail

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#769]
This feature would add a button or other UI mechanism that would enable an AC to manually and immediately trigger a Teaching Call reminder e-mail to anyone who hasn't completed their Teaching Call.

This would be triggered on a per-teaching call basis.

**Comment by cthielen** [comment]
Perhaps we should do our TC redesign to handle this.

**Comment by ltwheeler** [comment]
Addressed in #790
