### ISSUE TITLE
Add base class to set change tracking

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#866]
Add CreatedAt, UpdatedAt and ModifiedBy to a baseClass
Add CreatedAt, UpdatedAt and ModifiedBy to Course/SectionGroup/Section/Activity
Have those classes  inherit from the baseclass

The baseclass should make use of 
https://docs.jboss.org/hibernate/entitymanager/3.6/reference/en/html/listeners.html
to set those 3 values appropriately

**Comment by cthielen** [comment]
Let's add Workgroup, User, and UserRole to this list as well.
