### ISSUE TITLE
Add the ability to collect availability from support staff

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#947]
Chemistry cited this need:

Some workgroups simply collect the right amount of TAs for a section (or section series), and then let the instructor and TAs figure out the details of who will do what on their own.

Chemistry often plans and assigns TAs to a specific section in a series for their lower division large courses. They balance fitting everyone into a slot against the schedules of each TA.

Additionally, this feature would feed into the 'assign a support staff to a section' feature. With availability collected, our dropdown could automatically flag a person and a section as having a 'schedule conflict' potentially.

**Comment by cthielen** [comment]
We need to determine who and how many of our current customers want this. Please e-mail/call.

**Comment by cthielen** [comment]
Physics would like this too as would Ag & Resource Economics.

**Comment by ltwheeler** [comment]
Duplicate of #1398
