### ISSUE TITLE
1 | Reconciliation Report should show difference in the number of sections

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#980]
Remaining issues:
- [x] Should be able to mark non-ipa section as 'remove from banner'
- [x] Should be able to mark non-ipa section as create section in IPA
- [x] Tooltip UI for non-ipa section is being created in the wrong place on the screen
- [x] Service layer changes broke UI updating correctly when setting IPA to match banner value
- [x] Service layer changes broke routing to record IPA value on todo list
- [ ] Selecting IPA to match banner on instructors, should immediately update in UI
- [ ] Selecting section that does not exist in IPA to match banner, should create instructors/activites
-------------

The Reconciliation Report currently requires sections exist in order to compare, e.g. if I have no sections in IPA for ABC 101 but Banner has five sections, our report shows nothing. It really should show that Banner has five sections that we don't have.

**Comment by ltwheeler** [comment]
This should no longer be an issue, needs investigating
